### ISSUE TITLE
Palace order error

### ISSUE THREAD

**Issue by i-arun-samui** [waterfall531/ZiWeidoushu#2]
Hi,

palaces order doesn't seems to be accurate for any date,
as well as Emperor location, primary stars

if you can have a look

Thanks

**Comment by waterfall531** [comment]
sorry ,
I would appreciate it if you could type in Chinese

**Comment by i-arun-samui** [comment]
你好， 我已经测试了您的程序，但是对于我尝试过的所有日期，结果似乎都不准确。宫位位置不对，对应的宫位里没有星辰分布。 你能看看吗？ 谢谢

**Comment by waterfall531** [comment]
好的,
但我自己的命盤是沒有問題的
還是你可以貼個圖讓我了解一下你的宮位應該怎麼調整

**Comment by i-arun-samui** [comment]
你好，

它错误地解释了你的工作。 一切都是正确的。

谢谢
